### ISSUE TITLE
[IoT] Erro em removeContexResult()

### ISSUE THREAD

**Issue by LucasHMS** [AndreJCL/JCL#47]
Dado o seguinte contexto:

```
jclIoT.registerContext(device, sensor, new JCL_Expression("S0<1"), "test context");
ticket = jclIoT.addContextAction("test context", false, "userServices", "ordena", numbers);
ticket.get();
```

A chamada:
`jclIoT.removeContextResult("test context", ticket)`

retorna a seguinte exceção:

```
problem in JCL IoTfacade removeContextResult(String contextNickname, Long ticket)
RemoveContextResult false
java.lang.NumberFormatException: For input string: "null"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Short.parseShort(Short.java:118)
	at java.lang.Short.parseShort(Short.java:144)
	at implementations.dm_kernel.ConnectorImpl.sendReceiveG(ConnectorImpl.java:175)
	at implementations.dm_kernel.IoTuser.JCL_IoTFacadeImpl.removeContextResult(JCL_IoTFacadeImpl.java:682)
	at implementations.test.IoTuniTests1.testRemoveContextResult(IoTuniTests1.java:215)
	at implementations.test.IoTuniTests1.main(IoTuniTests1.java:333)
SetEncryption true
```

**Comment by leoscimino** [comment]
O problema foi corrigido
