### ISSUE TITLE
[IoT Android] Problema em Métodos sensingData 

### ISSUE THREAD

**Issue by LucasHMS** [AndreJCL/JCL#48]
Métodos getLastSensingData() e getSensingData() com o mesmo problema da versão IoT para as placas (Reportado em #45)

**Comment by LucasHMS** [comment]
Exceção do getLastSensigData() (que se repete no getSensingData()):

```
problem in JCL facade getLastSensingData(Entry<String, String> deviceNickname, Entry<String, String> sensorNickname)
java.lang.NumberFormatException: For input string: "no result"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at implementations.dm_kernel.IoTuser.JCL_IoTFacadeImpl.getLastSensingData(JCL_IoTFacadeImpl.java:230)
	at implementations.test.IoTuniTests.testGetLastSensingData(IoTuniTests.java:107)
	at implementations.test.IoTuniTests.main(IoTuniTests.java:293)
problem in JCL facade getSensingData(Entry<String, String> deviceNickname, Entry<String, String> sensorNickname)
java.lang.NumberFormatException: For input string: "no result"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at implementations.dm_kernel.IoTuser.JCL_IoTFacadeImpl.getSensingData(JCL_IoTFacadeImpl.java:199)
	at implementations.test.IoTuniTests.testGetSensingData(IoTuniTests.java:87)
	at implementations.test.IoTuniTests.main(IoTuniTests.java:295)
Exception in thread "main" java.lang.NullPointerException
	at implementations.test.IoTuniTests.testGetSensingData(IoTuniTests.java:87)
	at implementations.test.IoTuniTests.main(IoTuniTests.java:295) 
```

**Comment by leoscimino** [comment]
O problema foi solucionado.
